### ISSUE TITLE
Calendar opens in May 

### ISSUE THREAD

**Issue by olyfis** [MrGuiseppe/pureJSCalendar#2]
After the change to the New Year, the calendar opens in May instead of January.
The issue appears to be in the function switchMonth function.

![capture](https://user-images.githubusercontent.com/43828826/50606733-bff58c80-0e94-11e9-81d2-708afa9de7ca.JPG)

**Comment by MrGuiseppe** [comment]
Thank you for this nice issue ;) Month 0 translated into boolean false state
